server:
  port: 5002
spring:
  application:
    name: TASK-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/task_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # (Inferred)

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/